// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUserInput struct {
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Avatar   *string `json:"avatar,omitempty"`
	Plan     *string `json:"plan,omitempty"`
}

type Query struct {
}
